apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    support: IBM
    categories: "OpenShift Optional"
    containerImage: "ghcr.io/ocp-power-automation/rsct-operator:latest"
    repository: "https://github.com/ocp-power-automation/rsct-operator"
    description: Deploys RSCT daemonset on all nodes of an OpenShift cluster
  name: rsct-operator.v0.0.0
  namespace: rsct-operator-system
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: RSCT custom resource is the schema for the rscts API
      displayName: RSCT
      kind: RSCT
      name: rscts.rsct.ibm.com
      version: v1alpha1
  description: Deploys custom resource RSCT on all nodes of an OpenShift cluster.
  displayName: RSCT Operator for IBM Power Virtual Server
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: false
    type: AllNamespaces
  keywords:
  - rsct
  - powervs
  - ibm
  - rmc
  - power
  links:
  - name: Rsct Operator
    url: https://github.com/ocp-power-automation/rsct-operator
  maintainers:
  - email: mjturek@us.ibm.com
    name: Michael Turek
  maturity: alpha
  minKubeVersion: 1.25.0
  provider:
    name: IBM
  version: 0.0.0
